let productos = [
	{
		ID: 0,
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i3',
		Socket: ['1151', 'DDR3'],
		Imagen: '/img/i3.png',
		Precio: 160,
	},
	{
		ID: 1,
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i5',
		Socket: ['1151', 'DDR3'],
		Imagen: './img/i5.png',
		Precio: 235,
	},
	{
		ID: 2,
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i7',
		Socket: ['1200', 'DDR4'],
		Imagen: './img/i7.png',
		Precio: 320,
	},
	{
		ID: 3,
		Tipo: 'CPU',
		Marca: 'Intel Core',
		Serie: 'i9',
		Socket: ['1200', 'DDR4'],
		Imagen: './img/i9.png',
		Precio: 420,
	},
	{
		ID: 4,
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '3',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/r3.png',
		Precio: 200,
	},
	{
		ID: 5,
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '5',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/r5.png',
		Precio: 300,
	},
	{
		ID: 6,
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '7',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/r7.png',
		Precio: 400,
	},
	{
		ID: 7,
		Tipo: 'CPU',
		Marca: 'AMD Ryzen',
		Serie: '9',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/r9.png',
		Precio: 560,
	},
	{
		ID: 8,
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B85',
		Socket: ['1151', 'DDR3'],
		Imagen: './img/B85.png',
		Precio: 80,
	},
	{
		ID: 9,
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z370',
		Socket: ['1200', 'DDR4'],
		Imagen: './img/Z370.png',
		Precio: 130,
	},
	{
		ID: 10,
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'Z590',
		Socket: ['1200', 'DDR4'],
		Imagen: './img/Z590.png',
		Precio: 240,
	},
	{
		ID: 11,
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'B550',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/B550.png',
		Precio: 195,
	},
	{
		ID: 12,
		Tipo: 'Motherboard',
		Marca: 'Asus',
		Serie: 'X570',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/X570.png',
		Precio: 330,
	},
	{
		ID: 13,
		Tipo: 'Motherboard',
		Marca: 'Gigabyte',
		Serie: 'A570',
		Socket: ['AM4', 'DDR4'],
		Imagen: './img/A570.png',
		Precio: 250,
	},
	{
		ID: 14,
		Tipo: 'RAM',
		Marca: 'Kingston',
		Serie: 'Fury',
		Socket: ['All', 'DDR3'],
		Tamaño: '8',
		Imagen: './img/Fury.png',
		Precio: 80,
	},
	{
		ID: 15,
		Tipo: 'RAM',
		Marca: 'Kingston',
		Serie: 'Predator',
		Socket: ['All', 'DDR4'],
		Tamaño: '16',
		Imagen: './img/Predator.png',
		Precio: 150,
	},
];

export default productos;
